import { Retreat, Participant, Registration, PipelineStage } from './types';

export const seedRetreats: Retreat[] = [
  {
    id: 'retreat-1',
    retreatName: 'April 2026 – Big Sur',
    startDate: '2026-04-15',
    endDate: '2026-04-22',
    location: 'Big Sur, California',
    cohortSizeTarget: 8,
    status: 'Open',
    notes: 'Coastal retreat with ocean-view cabins.',
  },
  {
    id: 'retreat-2',
    retreatName: 'May 2026 – Tulum',
    startDate: '2026-05-10',
    endDate: '2026-05-17',
    location: 'Tulum, Mexico',
    cohortSizeTarget: 7,
    status: 'Open',
    notes: 'Beachfront eco-resort.',
  },
  {
    id: 'retreat-3',
    retreatName: 'June 2026 – Bali',
    startDate: '2026-06-08',
    endDate: '2026-06-15',
    location: 'Ubud, Bali',
    cohortSizeTarget: 9,
    status: 'Draft',
    notes: 'Rice terrace villa compound.',
  },
  {
    id: 'retreat-4',
    retreatName: 'July 2026 – Sedona',
    startDate: '2026-07-12',
    endDate: '2026-07-19',
    location: 'Sedona, Arizona',
    cohortSizeTarget: 6,
    status: 'Draft',
    notes: 'Desert wellness center.',
  },
];

export const seedParticipants: Participant[] = [
  {
    id: 'p-1',
    fullName: 'Elena Marchetti',
    email: 'elena@example.com',
    signalHandle: '@elena_m',
    allergies: 'Tree nuts',
    specialRequests: '',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'p-2',
    fullName: 'James Whitfield',
    email: 'james.w@example.com',
    signalHandle: '@jwhitfield',
    allergies: '',
    specialRequests: 'Ground-floor room preferred',
    createdAt: '2026-01-12T14:30:00Z',
  },
  {
    id: 'p-3',
    fullName: 'Anika Patel',
    email: 'anika.p@example.com',
    signalHandle: '@anika_patel',
    allergies: 'Gluten, dairy',
    specialRequests: 'Vegan meals only',
    createdAt: '2026-01-14T10:15:00Z',
  },
  {
    id: 'p-4',
    fullName: 'Marcus Chen',
    email: 'marcus.c@example.com',
    signalHandle: '@mchen',
    allergies: '',
    specialRequests: '',
    createdAt: '2026-01-18T08:45:00Z',
  },
  {
    id: 'p-5',
    fullName: 'Sofia Andersson',
    email: 'sofia.a@example.com',
    signalHandle: '@sofia_and',
    allergies: 'Shellfish',
    specialRequests: 'Quiet room',
    createdAt: '2026-01-20T16:00:00Z',
  },
  {
    id: 'p-6',
    fullName: 'David Okafor',
    email: 'david.o@example.com',
    signalHandle: '@dokafor',
    allergies: '',
    specialRequests: '',
    createdAt: '2026-01-22T11:30:00Z',
  },
  {
    id: 'p-7',
    fullName: 'Lucia Fernandez',
    email: 'lucia.f@example.com',
    signalHandle: '@lucia_fern',
    allergies: 'Soy',
    specialRequests: '',
    createdAt: '2026-01-25T09:00:00Z',
  },
  {
    id: 'p-8',
    fullName: 'Ryan Kowalski',
    email: 'ryan.k@example.com',
    signalHandle: '@ryanko',
    allergies: '',
    specialRequests: 'Late check-in (arriving midnight)',
    createdAt: '2026-01-28T13:20:00Z',
  },
  {
    id: 'p-9',
    fullName: 'Mei-Lin Wu',
    email: 'meilin.w@example.com',
    signalHandle: '@meilinwu',
    allergies: '',
    specialRequests: '',
    createdAt: '2026-02-01T07:45:00Z',
  },
  {
    id: 'p-10',
    fullName: 'Thomas Bergström',
    email: 'thomas.b@example.com',
    signalHandle: '@tbergstrom',
    allergies: 'Peanuts',
    specialRequests: 'Early morning meditation space',
    createdAt: '2026-02-03T15:10:00Z',
  },
];

function makeActivity(action: string, date: string, notes = '') {
  return {
    id: crypto.randomUUID(),
    date,
    action,
    notes,
    performedBy: 'Admin',
  };
}

function makeHistory(stages: PipelineStage[], startDate: string) {
  return stages.map((stage, i) => ({
    stage,
    date: new Date(new Date(startDate).getTime() + i * 2 * 86400000).toISOString(),
    note: '',
  }));
}

export const seedRegistrations: Registration[] = [
  // Retreat 1 — Big Sur
  {
    id: 'reg-1',
    retreatId: 'retreat-1',
    participantId: 'p-1',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-10'),
    lastTouchedAt: '2026-02-05T10:00:00Z',
    opsNotes: 'Very enthusiastic about the program.',
    tags: ['priority'],
    activities: [
      makeActivity('Lead added', '2026-01-10T09:00:00Z'),
      makeActivity('Chemistry call completed', '2026-01-15T14:00:00Z', 'Great conversation'),
      makeActivity('Application received', '2026-01-18T10:00:00Z'),
      makeActivity('Interview completed', '2026-01-22T11:00:00Z', 'Strong fit'),
      makeActivity('Approved', '2026-01-24T09:00:00Z'),
      makeActivity('Payment link sent', '2026-02-05T10:00:00Z'),
    ],
  },
  {
    id: 'reg-2',
    retreatId: 'retreat-1',
    participantId: 'p-2',
    currentStage: 'Accommodation Selection',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection'], '2026-01-12'),
    lastTouchedAt: '2026-02-04T16:00:00Z',
    opsNotes: '',
    tags: [],
    activities: [
      makeActivity('Lead added', '2026-01-12T14:30:00Z'),
      makeActivity('Paid in full', '2026-02-02T09:00:00Z'),
      makeActivity('Accommodation selection link sent', '2026-02-04T16:00:00Z'),
    ],
  },
  {
    id: 'reg-3',
    retreatId: 'retreat-1',
    participantId: 'p-3',
    currentStage: 'Interview',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview'], '2026-01-14'),
    lastTouchedAt: '2026-02-01T11:00:00Z',
    opsNotes: 'Needs dietary accommodations confirmed.',
    tags: ['dietary'],
    activities: [
      makeActivity('Lead added', '2026-01-14T10:15:00Z'),
      makeActivity('Interview scheduled', '2026-02-01T11:00:00Z'),
    ],
  },
  {
    id: 'reg-4',
    retreatId: 'retreat-1',
    participantId: 'p-4',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-03'),
    lastTouchedAt: '2026-02-03T08:45:00Z',
    opsNotes: '',
    tags: [],
    activities: [makeActivity('Lead added', '2026-02-03T08:45:00Z')],
  },
  // Retreat 2 — Tulum
  {
    id: 'reg-5',
    retreatId: 'retreat-2',
    participantId: 'p-5',
    currentStage: 'Online Course Link',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection', 'Online Course Link'], '2026-01-05'),
    lastTouchedAt: '2026-02-06T09:00:00Z',
    opsNotes: 'Fully onboarded.',
    tags: ['complete'],
    activities: [
      makeActivity('Lead added', '2026-01-05T09:00:00Z'),
      makeActivity('Course link sent', '2026-02-06T09:00:00Z'),
    ],
  },
  {
    id: 'reg-6',
    retreatId: 'retreat-2',
    participantId: 'p-6',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-01-22'),
    lastTouchedAt: '2026-01-28T14:00:00Z',
    opsNotes: '',
    tags: [],
    activities: [
      makeActivity('Lead added', '2026-01-22T11:30:00Z'),
      makeActivity('Chemistry call scheduled', '2026-01-28T14:00:00Z'),
    ],
  },
  {
    id: 'reg-7',
    retreatId: 'retreat-2',
    participantId: 'p-7',
    currentStage: 'Approval',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval'], '2026-01-10'),
    lastTouchedAt: '2026-02-03T10:00:00Z',
    opsNotes: 'Waiting for final approval review.',
    tags: ['review'],
    activities: [
      makeActivity('Lead added', '2026-01-10T09:00:00Z'),
      makeActivity('Interview completed', '2026-01-28T15:00:00Z', 'Pending review'),
    ],
  },
  // Retreat 3 — Bali
  {
    id: 'reg-8',
    retreatId: 'retreat-3',
    participantId: 'p-8',
    currentStage: 'Application',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application'], '2026-01-28'),
    lastTouchedAt: '2026-02-04T13:20:00Z',
    opsNotes: '',
    tags: [],
    activities: [
      makeActivity('Lead added', '2026-01-28T13:20:00Z'),
      makeActivity('Application submitted', '2026-02-04T13:20:00Z'),
    ],
  },
  {
    id: 'reg-9',
    retreatId: 'retreat-3',
    participantId: 'p-9',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-01'),
    lastTouchedAt: '2026-02-01T07:45:00Z',
    opsNotes: '',
    tags: [],
    activities: [makeActivity('Lead added', '2026-02-01T07:45:00Z')],
  },
  // Retreat 4 — Sedona
  {
    id: 'reg-10',
    retreatId: 'retreat-4',
    participantId: 'p-10',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-02-03'),
    lastTouchedAt: '2026-02-06T15:10:00Z',
    opsNotes: 'Has specific dietary needs.',
    tags: ['dietary'],
    activities: [
      makeActivity('Lead added', '2026-02-03T15:10:00Z'),
      makeActivity('Chemistry call link sent', '2026-02-06T15:10:00Z'),
    ],
  },
  {
    id: 'reg-11',
    retreatId: 'retreat-4',
    participantId: 'p-1',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-05'),
    lastTouchedAt: '2026-02-05T12:00:00Z',
    opsNotes: 'Returning participant from Big Sur.',
    tags: ['returning'],
    activities: [makeActivity('Lead added', '2026-02-05T12:00:00Z', 'Previous Big Sur attendee')],
  },
  {
    id: 'reg-12',
    retreatId: 'retreat-2',
    participantId: 'p-4',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T10:00:00Z',
    opsNotes: '',
    tags: [],
    activities: [makeActivity('Lead added', '2026-02-06T10:00:00Z')],
  },
];
