import {
  Retreat, Participant, Registration, Appointment, Task,
  PipelineStage, PaymentStatus, SchedulingStatus, RiskLevel, CareFlag,
} from './types';

const defaultRetreatFields = {
  capacityOverride: false,
  autoMarkFull: true,
  autoReopenWhenBelowCapacity: true,
  chemistryCallLink: '',
  applicationLink: '',
  paymentLink: '',
  accommodationSelectionLink: '',
  onlineCourseLink: '',
  accommodationOptions: [],
};

export const seedRetreats: Retreat[] = [
  {
    id: 'retreat-1',
    retreatName: 'March 13–16 – Boston',
    startDate: '2026-03-13',
    endDate: '2026-03-16',
    location: 'Boston, MA',
    cohortSizeTarget: 6,
    status: 'Open',
    notes: 'East-coast kickoff retreat.',
    ...defaultRetreatFields,
    chemistryCallLink: 'https://calendly.com/retreat-ops/chemistry-boston',
    applicationLink: 'https://forms.example.com/boston-apply',
    paymentLink: 'https://pay.example.com/boston-2026',
    accommodationSelectionLink: 'https://forms.example.com/boston-accom',
    onlineCourseLink: 'https://course.example.com/boston-prep',
    accommodationOptions: [
      { label: 'Harbor View Suite', description: 'Private suite with harbor views', priceAdjustment: 500 },
      { label: 'Brownstone Room', description: 'Classic brownstone-style room', priceAdjustment: 200 },
      { label: 'Shared Room', description: 'Shared room with one other participant', priceAdjustment: 0 },
    ],
  },
  {
    id: 'retreat-2',
    retreatName: 'March 30 – April 2 – Half Moon Bay',
    startDate: '2026-03-30',
    endDate: '2026-04-02',
    location: 'Half Moon Bay, CA',
    cohortSizeTarget: 6,
    status: 'Full',
    notes: 'Coastal retreat at the Ritz. Cohort is full!',
    ...defaultRetreatFields,
    chemistryCallLink: 'https://calendly.com/retreat-ops/chemistry-hmb-spring',
    paymentLink: 'https://pay.example.com/hmb-spring-2026',
    accommodationOptions: [
      { label: 'Ocean Terrace Suite', description: 'Suite with private ocean-view terrace', priceAdjustment: 400 },
      { label: 'Garden Room', description: 'Ground-floor room near gardens', priceAdjustment: 200 },
      { label: 'Coastal Room', description: 'Standard room with coastal views', priceAdjustment: 0 },
    ],
  },
  {
    id: 'retreat-3',
    retreatName: 'June 1–4 – Half Moon Bay',
    startDate: '2026-06-01',
    endDate: '2026-06-04',
    location: 'Half Moon Bay, CA',
    cohortSizeTarget: 6,
    capacityOverride: true,
    status: 'Open',
    notes: 'Early-summer cohort at the Ritz.',
    ...defaultRetreatFields,
    accommodationOptions: [
      { label: 'Ocean Terrace Suite', description: 'Suite with private ocean-view terrace', priceAdjustment: 600 },
      { label: 'Garden Room', description: 'Ground-floor room near gardens', priceAdjustment: 300 },
      { label: 'Coastal Room', description: 'Standard room with coastal views', priceAdjustment: 0 },
    ],
  },
  {
    id: 'retreat-4',
    retreatName: 'July 20–23 – Half Moon Bay',
    startDate: '2026-07-20',
    endDate: '2026-07-23',
    location: 'Half Moon Bay, CA',
    cohortSizeTarget: 6,
    status: 'Draft',
    notes: 'Midsummer cohort. Still planning.',
    ...defaultRetreatFields,
  },
  {
    id: 'retreat-5',
    retreatName: 'August 24–27 – Half Moon Bay',
    startDate: '2026-08-24',
    endDate: '2026-08-27',
    location: 'Half Moon Bay, CA',
    cohortSizeTarget: 6,
    status: 'Draft',
    notes: 'Late-summer cohort. Planning phase.',
    ...defaultRetreatFields,
  },
];

export const seedParticipants: Participant[] = [
  { id: 'p-1', fullName: 'Elena Marchetti', email: 'elena@example.com', signalHandle: '@elena_m', allergies: 'Tree nuts', specialRequests: '', createdAt: '2026-01-10T09:00:00Z' },
  { id: 'p-2', fullName: 'James Whitfield', email: 'james.w@example.com', signalHandle: '@jwhitfield', allergies: '', specialRequests: 'Ground-floor room preferred', createdAt: '2026-01-12T14:30:00Z' },
  { id: 'p-3', fullName: 'Anika Patel', email: 'anika.p@example.com', signalHandle: '@anika_patel', allergies: 'Gluten, dairy', specialRequests: 'Vegan meals only', createdAt: '2026-01-14T10:15:00Z' },
  { id: 'p-4', fullName: 'Marcus Chen', email: 'marcus.c@example.com', signalHandle: '@mchen', allergies: '', specialRequests: '', createdAt: '2026-01-18T08:45:00Z' },
  { id: 'p-5', fullName: 'Sofia Andersson', email: 'sofia.a@example.com', signalHandle: '@sofia_and', allergies: 'Shellfish', specialRequests: 'Quiet room', createdAt: '2026-01-20T16:00:00Z' },
  { id: 'p-6', fullName: 'David Okafor', email: 'david.o@example.com', signalHandle: '@dokafor', allergies: '', specialRequests: '', createdAt: '2026-01-22T11:30:00Z' },
  { id: 'p-7', fullName: 'Lucia Fernandez', email: 'lucia.f@example.com', signalHandle: '@lucia_fern', allergies: 'Soy', specialRequests: '', createdAt: '2026-01-25T09:00:00Z' },
  { id: 'p-8', fullName: 'Ryan Kowalski', email: 'ryan.k@example.com', signalHandle: '@ryanko', allergies: '', specialRequests: 'Late check-in (arriving midnight)', createdAt: '2026-01-28T13:20:00Z' },
  { id: 'p-9', fullName: 'Mei-Lin Wu', email: 'meilin.w@example.com', signalHandle: '@meilinwu', allergies: '', specialRequests: '', createdAt: '2026-02-01T07:45:00Z' },
  { id: 'p-10', fullName: 'Thomas Bergström', email: 'thomas.b@example.com', signalHandle: '@tbergstrom', allergies: 'Peanuts', specialRequests: 'Early morning meditation space', createdAt: '2026-02-03T15:10:00Z' },
  { id: 'p-11', fullName: 'Priya Sharma', email: 'priya.s@example.com', signalHandle: '@priya_s', allergies: '', specialRequests: 'Yoga mat in room', createdAt: '2026-01-05T12:00:00Z' },
  { id: 'p-12', fullName: 'Noah Bennett', email: 'noah.b@example.com', signalHandle: '@noahb', allergies: 'Dairy', specialRequests: '', createdAt: '2026-01-08T10:00:00Z' },
  { id: 'p-13', fullName: 'Isabelle Dupont', email: 'isabelle.d@example.com', signalHandle: '@isadupont', allergies: '', specialRequests: 'Airport transfer needed', createdAt: '2026-01-09T14:00:00Z' },
  { id: 'p-14', fullName: 'Kenji Tanaka', email: 'kenji.t@example.com', signalHandle: '@kenji_t', allergies: 'Eggs', specialRequests: '', createdAt: '2026-01-11T08:00:00Z' },
  { id: 'p-15', fullName: 'Clara Johansson', email: 'clara.j@example.com', signalHandle: '@claraj', allergies: '', specialRequests: 'Needs wheelchair access', createdAt: '2026-01-13T16:00:00Z' },
  { id: 'p-16', fullName: 'Omar Hassan', email: 'omar.h@example.com', signalHandle: '@omarh', allergies: '', specialRequests: '', createdAt: '2026-01-15T09:30:00Z' },
  { id: 'p-17', fullName: 'Zoe Mitchell', email: 'zoe.m@example.com', signalHandle: '@zoem', allergies: 'Sesame', specialRequests: 'Room with desk for work', createdAt: '2026-01-17T11:00:00Z' },
  { id: 'p-18', fullName: "Liam O'Brien", email: 'liam.ob@example.com', signalHandle: '@liamob', allergies: '', specialRequests: '', createdAt: '2026-01-19T13:00:00Z' },
  { id: 'p-19', fullName: 'Yuki Nakamura', email: 'yuki.n@example.com', signalHandle: '@yuki_n', allergies: '', specialRequests: 'Japanese-speaking facilitator preferred', createdAt: '2026-01-21T10:00:00Z' },
  { id: 'p-20', fullName: 'Amara Osei', email: 'amara.o@example.com', signalHandle: '@amarao', allergies: 'Latex', specialRequests: '', createdAt: '2026-01-23T14:00:00Z' },
  { id: 'p-21', fullName: 'Finn Larsen', email: 'finn.l@example.com', signalHandle: '@finnl', allergies: '', specialRequests: 'Early riser — 5am yoga access', createdAt: '2026-01-24T09:00:00Z' },
  { id: 'p-22', fullName: 'Camille Rossi', email: 'camille.r@example.com', signalHandle: '@camiller', allergies: 'Strawberries', specialRequests: '', createdAt: '2026-01-26T11:30:00Z' },
  { id: 'p-23', fullName: 'Raj Kapoor', email: 'raj.k@example.com', signalHandle: '@rajk', allergies: '', specialRequests: 'Vegetarian meals', createdAt: '2026-01-27T08:00:00Z' },
  { id: 'p-24', fullName: 'Natasha Volkov', email: 'natasha.v@example.com', signalHandle: '@natashav', allergies: '', specialRequests: 'Quiet room away from common areas', createdAt: '2026-01-29T16:00:00Z' },
];

function makeActivity(action: string, date: string, notes = '') {
  return { id: crypto.randomUUID(), date, action, notes, performedBy: 'Admin' };
}

function makeHistory(stages: PipelineStage[], startDate: string) {
  return stages.map((stage, i) => ({
    stage,
    date: new Date(new Date(startDate).getTime() + i * 2 * 86400000).toISOString(),
    note: '',
  }));
}

const defaultRegFields = {
  accommodationChoice: '',
  accommodationNotes: '',
  paymentStatus: 'Unpaid' as PaymentStatus,
  chemistryCallStatus: 'NotScheduled' as SchedulingStatus,
  interviewStatus: 'NotScheduled' as SchedulingStatus,
  riskLevel: 'None' as RiskLevel,
  careFlags: [] as CareFlag[],
  careNotes: '',
  careFlagOtherText: '',
};

export const seedRegistrations: Registration[] = [
  // ── Retreat 1 — Boston (Open, target 8, enrolled 3) ──
  {
    id: 'reg-1', retreatId: 'retreat-1', participantId: 'p-1',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-10'),
    lastTouchedAt: '2026-02-05T10:00:00Z', opsNotes: 'Very enthusiastic about the program.',
    tags: ['priority'], ...defaultRegFields, paymentStatus: 'Unpaid', amountDue: 3500,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    chemistryCallAppointmentId: 'apt-1', interviewAppointmentId: 'apt-2',
    riskLevel: 'Low', careFlags: ['Allergies'], careNotes: 'Tree nut allergy — ensure kitchen is notified.',
    flaggedAt: '2026-01-15T14:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-10T09:00:00Z'),
      makeActivity('Chemistry call completed', '2026-01-15T14:00:00Z', 'Great conversation'),
      makeActivity('Application received', '2026-01-18T10:00:00Z'),
      makeActivity('Interview completed', '2026-01-22T11:00:00Z', 'Strong fit'),
      makeActivity('Approved', '2026-01-24T09:00:00Z'),
      makeActivity('Payment link sent', '2026-02-05T10:00:00Z'),
    ],
  },
  {
    id: 'reg-2', retreatId: 'retreat-1', participantId: 'p-2',
    currentStage: 'Accommodation Selection',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection'], '2026-01-12'),
    lastTouchedAt: '2026-02-04T16:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 3500, amountPaid: 3500,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-12T14:30:00Z'),
      makeActivity('Paid in full', '2026-02-02T09:00:00Z'),
      makeActivity('Accommodation selection link sent', '2026-02-04T16:00:00Z'),
    ],
  },
  {
    id: 'reg-3', retreatId: 'retreat-1', participantId: 'p-3',
    currentStage: 'Interview',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview'], '2026-01-14'),
    lastTouchedAt: '2026-02-01T11:00:00Z', opsNotes: 'Needs dietary accommodations confirmed.',
    tags: ['dietary'], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Scheduled',
    interviewAppointmentId: 'apt-3',
    riskLevel: 'High', careFlags: ['Allergies', 'Dietary restrictions', 'Trauma-informed considerations'],
    careNotes: 'Multiple food allergies (gluten, dairy). Has mentioned past trauma — needs trauma-informed facilitation. Please review care plan before advancing.',
    flaggedAt: '2026-01-20T11:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-14T10:15:00Z'),
      makeActivity('Interview scheduled', '2026-02-01T11:00:00Z'),
    ],
  },
  {
    id: 'reg-4', retreatId: 'retreat-1', participantId: 'p-4',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-03'),
    lastTouchedAt: '2026-02-03T08:45:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-03T08:45:00Z')],
  },
  {
    id: 'reg-bs5', retreatId: 'retreat-1', participantId: 'p-11',
    currentStage: 'Online Course Link',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection', 'Online Course Link'], '2026-01-02'),
    lastTouchedAt: '2026-02-06T08:00:00Z', opsNotes: 'Fully onboarded.',
    tags: ['complete'], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 3500, amountPaid: 3500,
    accommodationChoice: 'Ocean View Cabin', accommodationPriceAdjustment: 500,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-02T09:00:00Z'),
      makeActivity('Payment confirmed', '2026-01-28T10:00:00Z'),
      makeActivity('Course link sent', '2026-02-06T08:00:00Z'),
    ],
  },
  {
    id: 'reg-bs6', retreatId: 'retreat-1', participantId: 'p-14',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-02-01'),
    lastTouchedAt: '2026-02-05T14:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Scheduled', chemistryCallAppointmentId: 'apt-4',
    activities: [
      makeActivity('Lead added', '2026-02-01T09:00:00Z'),
      makeActivity('Chemistry call scheduled', '2026-02-05T14:00:00Z'),
    ],
  },
  {
    id: 'reg-bs7', retreatId: 'retreat-1', participantId: 'p-15',
    currentStage: 'Application',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application'], '2026-01-20'),
    lastTouchedAt: '2026-02-03T16:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed',
    riskLevel: 'Medium', careFlags: ['Accessibility needs', 'Mobility concerns'],
    careNotes: 'Uses wheelchair — confirm venue accessibility.',
    flaggedAt: '2026-01-25T10:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-20T09:00:00Z'),
      makeActivity('Application submitted', '2026-02-03T16:00:00Z'),
    ],
  },
  {
    id: 'reg-bs8', retreatId: 'retreat-1', participantId: 'p-16',
    currentStage: 'Approval',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval'], '2026-01-15'),
    lastTouchedAt: '2026-02-04T10:00:00Z', opsNotes: 'Strong candidate', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-15T09:00:00Z'),
      makeActivity('Approved', '2026-02-04T10:00:00Z'),
    ],
  },

  // 6 new participants for retreat-1 (Big Sur)
  {
    id: 'reg-bs9', retreatId: 'retreat-1', participantId: 'p-19',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-05'),
    lastTouchedAt: '2026-02-05T09:00:00Z', opsNotes: 'Referred by Priya.',
    tags: ['referral'], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-05T09:00:00Z', 'Referral from Priya Sharma')],
  },
  {
    id: 'reg-bs10', retreatId: 'retreat-1', participantId: 'p-20',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-01-28'),
    lastTouchedAt: '2026-02-04T11:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Proposed',
    activities: [
      makeActivity('Lead added', '2026-01-28T09:00:00Z'),
      makeActivity('Chemistry call proposed', '2026-02-04T11:00:00Z'),
    ],
  },
  {
    id: 'reg-bs11', retreatId: 'retreat-1', participantId: 'p-21',
    currentStage: 'Application',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application'], '2026-01-22'),
    lastTouchedAt: '2026-02-02T15:00:00Z', opsNotes: 'Very motivated.',
    tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-22T09:00:00Z'),
      makeActivity('Chemistry call completed', '2026-01-28T10:00:00Z'),
      makeActivity('Application submitted', '2026-02-02T15:00:00Z'),
    ],
  },
  {
    id: 'reg-bs12', retreatId: 'retreat-1', participantId: 'p-22',
    currentStage: 'Interview',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview'], '2026-01-18'),
    lastTouchedAt: '2026-02-03T10:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Scheduled',
    riskLevel: 'Low', careFlags: ['Allergies'], careNotes: 'Strawberry allergy — check dessert menus.',
    flaggedAt: '2026-01-25T10:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-18T09:00:00Z'),
      makeActivity('Interview scheduled', '2026-02-03T10:00:00Z'),
    ],
  },
  {
    id: 'reg-bs13', retreatId: 'retreat-1', participantId: 'p-23',
    currentStage: 'Approval',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval'], '2026-01-12'),
    lastTouchedAt: '2026-02-05T16:00:00Z', opsNotes: 'Excellent interview.',
    tags: ['strong-fit'], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-12T09:00:00Z'),
      makeActivity('Approved', '2026-02-05T16:00:00Z'),
    ],
  },
  {
    id: 'reg-bs14', retreatId: 'retreat-1', participantId: 'p-24',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-08'),
    lastTouchedAt: '2026-02-06T10:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Partial', amountDue: 3500, amountPaid: 1750,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-08T09:00:00Z'),
      makeActivity('Partial payment received', '2026-02-06T10:00:00Z', '$1750 of $3500'),
    ],
  },

  // ── Retreat 2 — Half Moon Bay Spring (Full, target 7, enrolled 7) ──
  {
    id: 'reg-5', retreatId: 'retreat-2', participantId: 'p-5',
    currentStage: 'Online Course Link',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection', 'Online Course Link'], '2026-01-05'),
    lastTouchedAt: '2026-02-06T09:00:00Z', opsNotes: 'Fully onboarded.',
    tags: ['complete'], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 4000, amountPaid: 4000,
    accommodationChoice: 'Beachfront Palapa', accommodationPriceAdjustment: 400,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    riskLevel: 'Low', careFlags: ['Allergies'], careNotes: 'Shellfish allergy.',
    activities: [
      makeActivity('Lead added', '2026-01-05T09:00:00Z'),
      makeActivity('Course link sent', '2026-02-06T09:00:00Z'),
    ],
  },
  {
    id: 'reg-6', retreatId: 'retreat-2', participantId: 'p-6',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-10'),
    lastTouchedAt: '2026-02-03T14:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Unpaid', amountDue: 4000,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-10T11:30:00Z'),
      makeActivity('Payment link sent', '2026-02-03T14:00:00Z'),
    ],
  },
  {
    id: 'reg-7', retreatId: 'retreat-2', participantId: 'p-7',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-08'),
    lastTouchedAt: '2026-02-03T10:00:00Z', opsNotes: 'Waiting for payment.',
    tags: [], ...defaultRegFields, paymentStatus: 'Partial', amountDue: 4000, amountPaid: 2000,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-08T09:00:00Z'),
      makeActivity('Partial payment received', '2026-02-03T10:00:00Z', '$2000 of $4000'),
    ],
  },
  {
    id: 'reg-t4', retreatId: 'retreat-2', participantId: 'p-11',
    currentStage: 'Accommodation Selection',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection'], '2026-01-03'),
    lastTouchedAt: '2026-02-05T12:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 4000, amountPaid: 4000,
    accommodationChoice: 'Jungle Casita', accommodationPriceAdjustment: 200,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-03T09:00:00Z'),
      makeActivity('Accommodation selected', '2026-02-05T12:00:00Z'),
    ],
  },
  {
    id: 'reg-t5', retreatId: 'retreat-2', participantId: 'p-12',
    currentStage: 'Online Course Link',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection', 'Online Course Link'], '2026-01-02'),
    lastTouchedAt: '2026-02-06T10:00:00Z', opsNotes: '',
    tags: ['complete'], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 4000, amountPaid: 4000,
    accommodationChoice: 'Cenote Suite', accommodationPriceAdjustment: 300,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-02T09:00:00Z'),
      makeActivity('Course link sent', '2026-02-06T10:00:00Z'),
    ],
  },
  {
    id: 'reg-t6', retreatId: 'retreat-2', participantId: 'p-13',
    currentStage: 'Accommodation Selection',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection'], '2026-01-04'),
    lastTouchedAt: '2026-02-04T09:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 4000, amountPaid: 4000,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    riskLevel: 'Medium', careFlags: ['Rooming sensitivity', 'Interpersonal boundary needs'],
    careNotes: 'Prefers single room. Has specific boundary needs around group activities.',
    flaggedAt: '2026-01-20T10:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-04T09:00:00Z'),
      makeActivity('Payment confirmed', '2026-02-01T10:00:00Z'),
    ],
  },
  {
    id: 'reg-t7', retreatId: 'retreat-2', participantId: 'p-14',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-06'),
    lastTouchedAt: '2026-02-02T14:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Unpaid', amountDue: 4000,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    riskLevel: 'High', careFlags: ['Medical considerations', 'Dietary restrictions'],
    careNotes: 'Egg allergy (severe). Carries EpiPen. Ensure medical supplies nearby during retreat.',
    flaggedAt: '2026-01-12T08:00:00Z', flaggedBy: 'Admin',
    activities: [
      makeActivity('Lead added', '2026-01-06T09:00:00Z'),
      makeActivity('Payment link sent', '2026-02-02T14:00:00Z'),
    ],
  },
  {
    id: 'reg-t8', retreatId: 'retreat-2', participantId: 'p-4',
    currentStage: 'Approval',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval'], '2026-01-12'),
    lastTouchedAt: '2026-02-04T10:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [makeActivity('Lead added', '2026-01-12T10:00:00Z')],
  },
  {
    id: 'reg-t9', retreatId: 'retreat-2', participantId: 'p-18',
    currentStage: 'Interview',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview'], '2026-01-15'),
    lastTouchedAt: '2026-02-01T10:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Scheduled',
    interviewAppointmentId: 'apt-5',
    activities: [makeActivity('Lead added', '2026-01-15T09:00:00Z')],
  },

  // ── Retreat 3 — Half Moon Bay June (Open, target 9, enrolled 2) ──
  {
    id: 'reg-8', retreatId: 'retreat-3', participantId: 'p-8',
    currentStage: 'Application',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application'], '2026-01-28'),
    lastTouchedAt: '2026-02-04T13:20:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed',
    activities: [
      makeActivity('Lead added', '2026-01-28T13:20:00Z'),
      makeActivity('Application submitted', '2026-02-04T13:20:00Z'),
    ],
  },
  {
    id: 'reg-9', retreatId: 'retreat-3', participantId: 'p-9',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-01'),
    lastTouchedAt: '2026-02-01T07:45:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-01T07:45:00Z')],
  },
  {
    id: 'reg-b3', retreatId: 'retreat-3', participantId: 'p-16',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-01-25'),
    lastTouchedAt: '2026-02-03T10:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Scheduled', chemistryCallAppointmentId: 'apt-6',
    activities: [makeActivity('Lead added', '2026-01-25T09:00:00Z')],
  },
  {
    id: 'reg-b4', retreatId: 'retreat-3', participantId: 'p-17',
    currentStage: 'Interview',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview'], '2026-01-20'),
    lastTouchedAt: '2026-02-04T15:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Scheduled',
    interviewAppointmentId: 'apt-7',
    riskLevel: 'Low', careFlags: ['Dietary restrictions'], careNotes: 'Sesame allergy.',
    activities: [makeActivity('Lead added', '2026-01-20T09:00:00Z')],
  },
  {
    id: 'reg-b5', retreatId: 'retreat-3', participantId: 'p-18',
    currentStage: 'Approval',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval'], '2026-01-15'),
    lastTouchedAt: '2026-02-05T10:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [makeActivity('Lead added', '2026-01-15T09:00:00Z')],
  },
  {
    id: 'reg-b6', retreatId: 'retreat-3', participantId: 'p-1',
    currentStage: 'Payment',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment'], '2026-01-10'),
    lastTouchedAt: '2026-02-06T12:00:00Z', opsNotes: 'Returning from Big Sur.',
    tags: ['returning'], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 5000, amountPaid: 5000,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [makeActivity('Lead added', '2026-01-10T09:00:00Z')],
  },
  {
    id: 'reg-b7', retreatId: 'retreat-3', participantId: 'p-2',
    currentStage: 'Accommodation Selection',
    stageHistory: makeHistory(['Leads', 'Chemistry Call', 'Application', 'Interview', 'Approval', 'Payment', 'Accommodation Selection'], '2026-01-08'),
    lastTouchedAt: '2026-02-06T14:00:00Z', opsNotes: '',
    tags: [], ...defaultRegFields, paymentStatus: 'Paid', amountDue: 5000, amountPaid: 5000,
    accommodationChoice: 'Rice Terrace Room', accommodationPriceAdjustment: 300,
    chemistryCallStatus: 'Completed', interviewStatus: 'Completed',
    activities: [makeActivity('Lead added', '2026-01-08T09:00:00Z')],
  },
  {
    id: 'reg-b8', retreatId: 'retreat-3', participantId: 'p-6',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-05'),
    lastTouchedAt: '2026-02-05T11:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-05T11:00:00Z')],
  },
  {
    id: 'reg-b9', retreatId: 'retreat-3', participantId: 'p-10',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-02-02'),
    lastTouchedAt: '2026-02-06T09:00:00Z', opsNotes: '', tags: ['dietary'], ...defaultRegFields,
    chemistryCallStatus: 'Proposed',
    activities: [makeActivity('Lead added', '2026-02-02T09:00:00Z')],
  },
  {
    id: 'reg-b10', retreatId: 'retreat-3', participantId: 'p-15',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T16:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-06T16:00:00Z')],
  },

  // ── Retreat 4 — Half Moon Bay July (Draft, target 6) ──
  {
    id: 'reg-10', retreatId: 'retreat-4', participantId: 'p-10',
    currentStage: 'Chemistry Call',
    stageHistory: makeHistory(['Leads', 'Chemistry Call'], '2026-02-03'),
    lastTouchedAt: '2026-02-06T15:10:00Z', opsNotes: 'Has specific dietary needs.',
    tags: ['dietary'], ...defaultRegFields,
    activities: [
      makeActivity('Lead added', '2026-02-03T15:10:00Z'),
      makeActivity('Chemistry call link sent', '2026-02-06T15:10:00Z'),
    ],
  },
  {
    id: 'reg-11', retreatId: 'retreat-4', participantId: 'p-1',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-05'),
    lastTouchedAt: '2026-02-05T12:00:00Z', opsNotes: 'Returning participant.',
    tags: ['returning'], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-05T12:00:00Z', 'Previous Boston attendee')],
  },
  {
    id: 'reg-s3', retreatId: 'retreat-4', participantId: 'p-3',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-04'),
    lastTouchedAt: '2026-02-04T09:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-04T09:00:00Z')],
  },
  {
    id: 'reg-s4', retreatId: 'retreat-4', participantId: 'p-5',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-05'),
    lastTouchedAt: '2026-02-05T10:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-05T10:00:00Z')],
  },

  // ── Retreat 5 — Half Moon Bay August (Draft, target 8) ──
  {
    id: 'reg-s5', retreatId: 'retreat-5', participantId: 'p-7',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T08:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-06T08:00:00Z')],
  },
  {
    id: 'reg-s6', retreatId: 'retreat-5', participantId: 'p-9',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T11:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-06T11:00:00Z')],
  },
  {
    id: 'reg-s7', retreatId: 'retreat-5', participantId: 'p-12',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T14:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-06T14:00:00Z')],
  },
  {
    id: 'reg-s8', retreatId: 'retreat-5', participantId: 'p-13',
    currentStage: 'Leads',
    stageHistory: makeHistory(['Leads'], '2026-02-06'),
    lastTouchedAt: '2026-02-06T15:00:00Z', opsNotes: '', tags: [], ...defaultRegFields,
    activities: [makeActivity('Lead added', '2026-02-06T15:00:00Z')],
  },
];

// Seed appointments
export const seedAppointments: Appointment[] = [
  {
    id: 'apt-1', retreatId: 'retreat-1', registrationId: 'reg-1', type: 'ChemistryCall',
    startDateTime: '2026-01-15T14:00:00Z', endDateTime: '2026-01-15T14:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Completed',
    locationOrLink: 'https://zoom.us/j/1234567890', notes: 'Great conversation, strong fit.',
    createdAt: '2026-01-13T10:00:00Z', updatedAt: '2026-01-15T14:30:00Z',
  },
  {
    id: 'apt-2', retreatId: 'retreat-1', registrationId: 'reg-1', type: 'Interview',
    startDateTime: '2026-01-22T11:00:00Z', endDateTime: '2026-01-22T11:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Completed',
    locationOrLink: 'https://zoom.us/j/9876543210', notes: 'Approved for retreat.',
    createdAt: '2026-01-18T10:00:00Z', updatedAt: '2026-01-22T11:30:00Z',
  },
  {
    id: 'apt-3', retreatId: 'retreat-1', registrationId: 'reg-3', type: 'Interview',
    startDateTime: '2026-02-10T15:00:00Z', endDateTime: '2026-02-10T15:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Scheduled',
    locationOrLink: 'https://zoom.us/j/1112223333', notes: 'Review dietary needs during interview.',
    createdAt: '2026-02-01T11:00:00Z', updatedAt: '2026-02-01T11:00:00Z',
  },
  {
    id: 'apt-4', retreatId: 'retreat-1', registrationId: 'reg-bs6', type: 'ChemistryCall',
    startDateTime: '2026-02-08T10:00:00Z', endDateTime: '2026-02-08T10:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Scheduled',
    locationOrLink: 'https://calendly.com/retreat-ops/chemistry-bigsur', notes: '',
    createdAt: '2026-02-05T14:00:00Z', updatedAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'apt-5', retreatId: 'retreat-2', registrationId: 'reg-t9', type: 'Interview',
    startDateTime: '2026-02-09T16:00:00Z', endDateTime: '2026-02-09T16:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Scheduled',
    locationOrLink: 'https://zoom.us/j/4445556666', notes: '',
    createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'apt-6', retreatId: 'retreat-3', registrationId: 'reg-b3', type: 'ChemistryCall',
    startDateTime: '2026-02-11T09:00:00Z', endDateTime: '2026-02-11T09:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Scheduled',
    locationOrLink: 'https://zoom.us/j/7778889999', notes: '',
    createdAt: '2026-02-03T10:00:00Z', updatedAt: '2026-02-03T10:00:00Z',
  },
  {
    id: 'apt-7', retreatId: 'retreat-3', registrationId: 'reg-b4', type: 'Interview',
    startDateTime: '2026-02-12T14:00:00Z', endDateTime: '2026-02-12T14:30:00Z',
    timezone: 'America/Los_Angeles', status: 'Scheduled',
    locationOrLink: 'https://zoom.us/j/0001112222', notes: 'Check sesame allergy accommodations.',
    createdAt: '2026-02-04T15:00:00Z', updatedAt: '2026-02-04T15:00:00Z',
  },
];

// Seed tasks
export const seedTasks: Task[] = [
  {
    id: 'task-1', retreatId: 'retreat-1', registrationId: 'reg-3',
    title: 'Risk & Care review — Anika Patel',
    description: 'Review care plan for trauma-informed facilitation before advancing to Approval.',
    dueDate: '2026-02-09', status: 'Open', priority: 'High',
    createdAt: '2026-01-20T11:00:00Z', updatedAt: '2026-01-20T11:00:00Z',
  },
  {
    id: 'task-2', retreatId: 'retreat-1', registrationId: 'reg-bs7',
    title: 'Confirm wheelchair accessibility',
    description: 'Verify Boston venue can accommodate wheelchair needs. Contact venue manager.',
    dueDate: '2026-02-15', status: 'Open', priority: 'High',
    createdAt: '2026-01-25T10:00:00Z', updatedAt: '2026-01-25T10:00:00Z',
  },
  {
    id: 'task-3', retreatId: 'retreat-2', registrationId: 'reg-t6',
    title: 'Rooming sensitivity review',
    description: 'Ensure Isabelle has a single room and review boundary accommodations.',
    dueDate: '2026-02-20', status: 'Open', priority: 'Medium',
    createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'task-4', retreatId: 'retreat-2', registrationId: 'reg-t7',
    title: 'Medical supplies prep — Kenji',
    description: 'Confirm EpiPen availability and brief staff on egg allergy emergency protocol.',
    dueDate: '2026-03-01', status: 'Open', priority: 'High',
    createdAt: '2026-01-12T08:00:00Z', updatedAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'task-5', retreatId: 'retreat-1', registrationId: 'reg-1',
    title: 'Follow up on payment — Elena',
    description: 'Elena has not completed payment. Send a reminder.',
    dueDate: '2026-02-08', status: 'Done', priority: 'Medium',
    createdAt: '2026-02-05T10:00:00Z', updatedAt: '2026-02-06T09:00:00Z',
    completedAt: '2026-02-06T09:00:00Z',
  },
];
