project_id = "ofgdycudacoqvkxtbadr"

[functions.send-email]
verify_jwt = false

[functions.send-signal]
verify_jwt = false

[functions.sync-email-inbound]
verify_jwt = false

[functions.signal-inbound]
verify_jwt = false

[functions.sync-vimeo]
verify_jwt = false
